/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as ReceitasNomesETiposRouteImport } from './routes/receitas.nomes-e-tipos'
import { Route as ReceitasSlugRouteImport } from './routes/receitas.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRoute,
} as any)
const ReceitasNomesETiposRoute = ReceitasNomesETiposRouteImport.update({
  id: '/nomes-e-tipos',
  path: '/nomes-e-tipos',
  getParentRoute: () => ReceitasRoute,
} as any)
const ReceitasSlugRoute = ReceitasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReceitasRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
  '/receitas/nomes-e-tipos': typeof ReceitasNomesETiposRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
  '/receitas/nomes-e-tipos': typeof ReceitasNomesETiposRoute
  '/categorias': typeof CategoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
  '/receitas/nomes-e-tipos': typeof ReceitasNomesETiposRoute
  '/categorias/': typeof CategoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/contato'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/categorias/$slug'
    | '/receitas/$slug'
    | '/receitas/nomes-e-tipos'
    | '/categorias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/categorias/$slug'
    | '/receitas/$slug'
    | '/receitas/nomes-e-tipos'
    | '/categorias'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/contato'
    | '/receitas'
    | '/sitemap.xml'
    | '/sobre'
    | '/categorias/$slug'
    | '/receitas/$slug'
    | '/receitas/nomes-e-tipos'
    | '/categorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ReceitasRoute: typeof ReceitasRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/receitas/nomes-e-tipos': {
      id: '/receitas/nomes-e-tipos'
      path: '/nomes-e-tipos'
      fullPath: '/receitas/nomes-e-tipos'
      preLoaderRoute: typeof ReceitasNomesETiposRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/receitas/$slug': {
      id: '/receitas/$slug'
      path: '/$slug'
      fullPath: '/receitas/$slug'
      preLoaderRoute: typeof ReceitasSlugRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ReceitasRouteChildren {
  ReceitasSlugRoute: typeof ReceitasSlugRoute
  ReceitasNomesETiposRoute: typeof ReceitasNomesETiposRoute
}

const ReceitasRouteChildren: ReceitasRouteChildren = {
  ReceitasSlugRoute: ReceitasSlugRoute,
  ReceitasNomesETiposRoute: ReceitasNomesETiposRoute,
}

const ReceitasRouteWithChildren = ReceitasRoute._addFileChildren(
  ReceitasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ReceitasRoute: ReceitasRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
